#### October 2, 2025
I'm officially starting my postdoc at Wharton, working with an amazing interdisciplinary team: Stefano Puntoni (Marketing), Angela Duckworth (Psychology, OID), Lyle Ungar (Computer Science).

#### September 25, 2025
I posted an updated preprint for my job market paper on [ArXiv](https://arxiv.org/pdf/2502.02880).

#### August 29, 2025
Successfully defended my dissertation. See recording [here], [slides], and [PDF].

#### May 19, 2025
I started an internship at Microsoft Research! 
I'm working with [Dan Goldstein](https://www.dangoldstein.com) in the Computational Social Science group. 
We're working, along with (Jaeyoon Song)[jaeyoon.io], on AI and human forecasting.

#### May 5, 2025
I won the Psychology of Technology Dissertation Award!

#### Feb 8, 2024
I'm at SPSP!

#### Novemeber 3, 2023
Lyle Ungar is presenting a talk on [C](https://docs.google.com/presentation/d/1uBJ-QEi5HdSsGPWpj4m39iUbypWwS1dt/edit#slide=id.p1) at the [Psychology of Technology Conference](https://www.psychoftech.org/2023-conference#:~:text=The%20USC%20Marshall's%20Neely%20Center,sponsored%20by%20the%20University%20of)!

#### October 12, 2023
Our paper on Using AI to Measure Personal Qualities in Admissions was published at Science Advances today. Check it out [here](https://www.science.org/doi/10.1126/sciadv.adg9405).

#### March 14, 2023
I was invited to [Counselor Bites](https://www.collegeguidancenetwork.com), to talk about the future of AI in College admissions with Brennan Barnard and Jenny Rickard, CEO of CommonApp. See the recorded conversation [here](https://www.library.collegeguidancenetwork.com/library/resources/video/ccb7e7c4-b0bf-4981-b6cb-2ec2cfb371df), and resources from the program [here](https://www.library.collegeguidancenetwork.com/library/resources/pdf/e7068264-df60-4d9b-a302-2e418cbe32b9).

#### Summer, 2022
I am participating in the [Summer Institute in Computational Social Science](https://sicss.io).