---
title: "Publications"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

My current number of citations is 643, and my h-index is 9.

### Job Market Paper
Under review at *Nature Communications*.

Lira, B., Goldstein, D., Rogers, T., Ungar, L., & Duckworth, A. L. *Coach not Crutch: AI assistance can enhance rather than hinder skill development.* [[ArXiv]](https://arxiv.org/pdf/2502.02880)

### Published

**Lira, B.**, Duckworth, A. L., Gardner, M., Quirk, A., Stone, C., Rao, A., ... & D’Mello, S. K. (2023). Using Artificial Intelligence to Assess Personal Qualities in College Admissions. *Science Advances*. [[link]](https://www.science.org/doi/pdf/10.1126/sciadv.adg9405)

Lira, B., O’Brien, J., Peña, P.A., Galla, B.M., D’Mello, S., Yeager, D.S., Defnet, A., Kautz, T., Munkacsy, K., Duckworth, A.L.,
(2022). Large Studies Reveal How Reference Bias Limits Policy Applications of Self-Report Measures. Scientific Reports
12(1) 19189. [[link]](https://www.nature.com/articles/s41598-022-23373-9)

Putnam, S. P., Sehic, E., French, B. F., Gartstein, M. A., **Lira, B.**, & Peltola, M. (2024). The Global Temperament Project: Parent-Reported Temperament in Infants, Toddlers and Children from 59 Nations. *Developmental Psychology*. [link]

Duckworth, A. L., Kautz, T., Defnet, A., Satlof-Bedrick, E., Talamas, S., **Lira, B.**, & Steinberg, L. (2021). Students attending school remotely suffer socially, emotionally, and academically. *Educational Researcher, 50*(7), 479–482. [[PsyArXiv]](https://mfr.osf.io/export?format=pdf&url=https%3A//files.osf.io/v1/resources/rpz7h/providers/osfstorage/60216615339cb6013acf0da8%3Fformat%3Dpdf%26action%3Ddownload%26direct%26version%3D1) [[PDF]](https://journals.sagepub.com/doi/epdf/10.3102/0013189X211031551)

### Under Review

Lira, B., Song, J., Alsobay, M., & Goldstein, D. *Forecasting with LLMs: A Dataset for Rapid Backtesting Without Temporal Contamination.* Submitted to ICLR 2026.

### In Preparation
Lira, B., Castelo, N., Toubia, O., & Puntoni, S. *Synthetic Contact: Digital Twins as a Scalable Tool for Consumer Insight and Reducing Partisan Misperceptions.*

Sungu, A., Lira, B., & Duckworth, A. L. *Performance gains, motivational pains: Evidence from AI adoption in Turkish teachers.*

Lira, B., Goldstein, D., Rogers, T., Ungar, L., & Duckworth, A. L. *Smart and Smarter: Pairing AI examples and metacognition improves writing skill.*

Lira, B., Ungar, L., Gross, J., & Duckworth, A. L. *Delivering motivational interventions at scale using Artificial Intelligence in Khan Academy.*

Lira, B., Ungar, L., & Duckworth, A. L. *Conversing with a Generative-AI powered chatbot increases critical thinking.*